name: pull request
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint-format-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Requirements
        run: pip install -r requirements/dev.txt
      - name: Test upgrading pip
        run: pip install --upgrade pylint numpy mypy
      - name: Pylint
        run: pylint src/
      - name: Black
        run: black --check ./
      - name: Type Check (mypy)
        run: mypy src --strict
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Requirements
        run: pip install -r requirements/dev.txt
      - name: Unit Tests
        run: python -m pytest tests/unit
  unit-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Requirements
        run: pip install -r requirements/dev.txt
      - name: "Setup jq"
        uses: dcarbone/install-jq-action@v1.0.1
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Preset up execution environment
        run: |
          git submodule update --init --recursive
      - name: Copy Lean4Repl
        run: |
          cp -r Lean4Repl/ execution_env/
      - name: Build Lean4Repl
        run: |
          cd execution_env
          lake build Lean4Repl
      - name: Get mathlib dep
        run: |
          cd execution_env
          lake exe cache get
      - name: e2e Tests
        run: python -m pytest tests/e2e
